CREATE DATABASE ECOLOG;
USE ECOLOG;

CREATE TABLE TIPO_CONTATO (
	COD_TIPO_CONTATO INT PRIMARY KEY AUTO_INCREMENT, 
	DESC_CONTATO VARCHAR(100) NOT NULL, 
	STATUS_TIPO_CONTATO INT DEFAULT 1
);

INSERT INTO TIPO_CONTATO (DESC_CONTATO) VALUES ('Fixo'), ('Comercial'), ('Celular'), ('E-mail'), ('Telefone para recado');

CREATE TABLE TIPO_USUARIO (
	COD_TIPO_USUARIO INT PRIMARY KEY AUTO_INCREMENT, 
	NOME_TIPO_USUARIO VARCHAR(100) NOT NULL, 
	STATUS_TIPO_USUARIO INT DEFAULT 1
);

INSERT INTO TIPO_USUARIO (NOME_TIPO_USUARIO) VALUES ('Administrador'), ('Coletor'), ('Empresa'), ('Comum');

CREATE TABLE TIPO_DOCUMENTO(
	COD_TIPO_DOCUMENTO INT PRIMARY KEY AUTO_INCREMENT, 
	NOME_TIPO_DOCUMENTO VARCHAR(100) NOT NULL, 
	STATUS_TIPO_DOCUMENTO INT DEFAULT 1
);

INSERT INTO TIPO_DOCUMENTO (NOME_TIPO_DOCUMENTO) VALUES ('RG'), ('CPF'), ('CNH'), ('INSCRICAO ESTADUAL');


CREATE TABLE USUARIO (
	COD_USUARIO INT PRIMARY KEY AUTO_INCREMENT, 
	NOME_USUARIO VARCHAR(100) NOT NULL, 
	LOGIN_USUARIO VARCHAR(50) NOT NULL, 
	SENHA_USUARIO VARCHAR(100) NOT NULL, 
   	DOC_USUARIO VARCHAR(20) NOT NULL, 
	CEP_USUARIO CHAR(8) NULL, 
   	NUM_USUARIO VARCHAR(15) NULL, 
	COMPLEMENTO_USUARIO VARCHAR(255) NULL, 
	COD_TIPO_USUARIO INT, 
    COD_TIPO_DOCUMENTO INT,
	STATUS_USUARIO INT DEFAULT 1,
	URL_FOTO_USUARIO VARCHAR(255),
	LONGITUDE_USUARIO VARCHAR(20) NOT NULL, 
	LATITUDE_USUARIO VARCHAR(20) NOT NULL,  
	FOREIGN KEY (COD_TIPO_USUARIO) REFERENCES TIPO_USUARIO (COD_TIPO_USUARIO),
    FOREIGN KEY (COD_TIPO_DOCUMENTO) REFERENCES TIPO_DOCUMENTO (COD_TIPO_DOCUMENTO)
);

CREATE TABLE CONTATO (
	COD_CONTATO INT PRIMARY KEY AUTO_INCREMENT, 
	CONTATO VARCHAR(100) NOT NULL, 
	STATUS_CONTATO INT DEFAULT 1, 
	COD_TIPO_CONTATO INT NOT NULL, 
	COD_USUARIO INT NOT NULL,
	FOREIGN KEY (COD_TIPO_CONTATO) REFERENCES TIPO_CONTATO (COD_TIPO_CONTATO),
	FOREIGN KEY (COD_USUARIO) REFERENCES USUARIO (COD_USUARIO)
);

CREATE TABLE ROTA (
	COD_ROTA INT PRIMARY KEY AUTO_INCREMENT, 
	CEP_INICIAL_ROTA CHAR(8) NOT NULL, 
	LATITUDE_INICIAL_ROTA VARCHAR(20) NOT NULL, 
	LONGITUDE_INICIAL_ROTA VARCHAR(20) NOT NULL, 
	CEP_FINAL_ROTA CHAR(8) NOT NULL, 
	LONGITUDE_FINAL_ROTA VARCHAR(20) NOT NULL, 
	LATITUDE_FINAL_ROTA VARCHAR(20) NOT NULL, 
   	DATA_CAD_ROTA DATETIME NOT NULL, 
	OBS_ROTA VARCHAR(150) NOT NULL, 
	COD_USUARIO INT NOT NULL, 
	STATUS_ROTA INT DEFAULT 1,
	FOREIGN KEY (COD_USUARIO) REFERENCES USUARIO (COD_USUARIO)
);

CREATE TABLE CATEGORIA (
	COD_CATEGORIA INT PRIMARY KEY AUTO_INCREMENT, 
	NOME_CATEGORIA VARCHAR(80) NOT NULL, 
	STATUS_CATEGORIA INT DEFAULT 1
);

INSERT INTO CATEGORIA (NOME_CATEGORIA) VALUES ('Plastico'), ('Metal'), ('Papel'), ('Vidro');

CREATE TABLE  MATERIAL (
	COD_MATERIAL INT PRIMARY KEY AUTO_INCREMENT, 
	NOME_MATERIAL VARCHAR(80) NOT NULL, 
	DESC_MATERIAL VARCHAR(100) NOT NULL, 
	COD_CATEGORIA INT, 
	STATUS_MATERIAL INT DEFAULT 1,
	FOREIGN KEY (COD_CATEGORIA) REFERENCES CATEGORIA (COD_CATEGORIA)
);

CREATE TABLE ECOPONTO (
	COD_ECOPONTO INT PRIMARY KEY AUTO_INCREMENT, 
	NOME_ECOPONTO VARCHAR(80) NOT NULL, 
	HORARIO_FUNC_ECOPONTO VARCHAR(30) NOT NULL, 
	CEP_ECOPONTO CHAR(8) NOT NULL, 
   	LONGITUDE_ECOPONTO VARCHAR(20) NOT NULL,  
	LATITUDE_ECOPONTO VARCHAR(20) NOT NULL, 
   	NUM_ECOPONTO CHAR(10) NOT NULL, 
	COMPLEMENTO_ECOPONTO VARCHAR(150) NULL, 
	STATUS_ECOPONTO INT DEFAULT 1
);

CREATE TABLE USU_COLETA_MATERIAL (
	COD_USUARIO INT NOT NULL, 
	COD_MATERIAL INT NOT NULL,
	PRIMARY KEY (COD_USUARIO, COD_MATERIAL), 
	FOREIGN KEY (COD_USUARIO) REFERENCES USUARIO (COD_USUARIO), 
	FOREIGN KEY (COD_MATERIAL) REFERENCES MATERIAL (COD_MATERIAL)
);

CREATE TABLE USU_COMPRA_MATERIAL (
	COD_USUARIO INT NOT NULL, 
	COD_MATERIAL INT NOT NULL, 
	VALOR_COMPRADO NUMERIC(10,2) NULL,
	OBS_COMPRA VARCHAR(100) NULL, 
	PRIMARY KEY (COD_USUARIO, COD_MATERIAL), 
	FOREIGN KEY (COD_USUARIO) REFERENCES USUARIO (COD_USUARIO),
	FOREIGN KEY (COD_MATERIAL) REFERENCES MATERIAL (COD_MATERIAL)
);

CREATE TABLE USU_FAVORITA_ECOPONTO (
	COD_USUARIO INT NOT NULL, 
	COD_ECOPONTO INT NOT NULL, 
	DATA_HORA_FAVORITA DATETIME NOT NULL, 
	PRIMARY KEY (COD_USUARIO, COD_ECOPONTO), 
	FOREIGN KEY (COD_USUARIO) REFERENCES USUARIO (COD_USUARIO), 
	FOREIGN KEY (COD_ECOPONTO) REFERENCES ECOPONTO (COD_ECOPONTO)
);

CREATE TABLE USU_AVALIA_ECOPONTO (
	COD_USUARIO INT NOT NULL, 
	COD_ECOPONTO INT NOT NULL, 
	NOTA_AVALIACAO NUMERIC (5,2) NOT NULL,
        OBS_AVALIACAO VARCHAR (255) NULL, 
	DATA_HORA_AVALIACAO DATETIME NOT NULL, 
	PRIMARY KEY (COD_USUARIO, COD_ECOPONTO), 
	FOREIGN KEY (COD_USUARIO) REFERENCES USUARIO (COD_USUARIO), 
	FOREIGN KEY (COD_ECOPONTO) REFERENCES ECOPONTO (COD_ECOPONTO)
);

CREATE TABLE ECOPONTO_RECEBE_MATERIAL (
	COD_ECOPONTO INT NOT NULL, 
	COD_MATERIAL INT NOT NULL, 
	PRIMARY KEY (COD_ECOPONTO, COD_MATERIAL), 
	FOREIGN KEY (COD_ECOPONTO) REFERENCES ECOPONTO (COD_ECOPONTO), 
	FOREIGN KEY (COD_MATERIAL) REFERENCES MATERIAL (COD_MATERIAL)
);

CREATE TABLE HASH_SENHA (
	HASH_SENHA VARCHAR(255) NOT NULL, 
    DATA_GERACAO DATETIME, 
    COD_USUARIO INTEGER NOT NULL, 
    CONSTRAINT PRIMARY KEY (HASH_SENHA, DATA_GERACAO, COD_USUARIO),
    CONSTRAINT FOREIGN KEY (COD_USUARIO) REFERENCES USUARIO (COD_USUARIO)
);